In [1]:
#Brittany Roberts
#DSC410
#Milestone 3: Feature Engineering

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

disease_data = pd.read_csv("C:\\Users\\Brittany\\OneDrive - Bellevue University\\Data Sources\\Disease_symptom_and_patient_profile_dataset.csv")
disease_data

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,Yes,No,Yes,Yes,19,Female,Low,Normal,Positive
1,Common Cold,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
2,Eczema,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
3,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
4,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
...,...,...,...,...,...,...,...,...,...,...
344,Stroke,Yes,No,Yes,No,80,Female,High,High,Positive
345,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
346,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
347,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive
348,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive

In [3]:
count = disease_data['Disease'].value_counts()
percent = 100*disease_data['Disease'].value_counts(normalize=True)
df=pd.DataFrame({'count':count, 'percent':percent.round(1)})
print(df)

                                count  percent
Asthma                             23      6.6
Stroke                             16      4.6
Osteoporosis                       14      4.0
Hypertension                       10      2.9
Diabetes                           10      2.9
...                               ...      ...
Autism Spectrum Disorder (ASD)      1      0.3
Hypoglycemia                        1      0.3
Fibromyalgia                        1      0.3
Eating Disorders (Anorexia,...      1      0.3
Williams Syndrome                   1      0.3

[116 rows x 2 columns]

In [4]:
#Looking to use the 10 top most diagnosed diseases as test data.

df_10 = df.iloc[:10]
df_10

                 count  percent
Asthma              23      6.6
Stroke              16      4.6
Osteoporosis        14      4.0
Hypertension        10      2.9
Diabetes            10      2.9
Migraine            10      2.9
Influenza            8      2.3
Pneumonia            8      2.3
Bronchitis           8      2.3
Hyperthyroidism      7      2.0

In [9]:
new_df = disease_data[(disease_data['Disease'] == 'Asthma') | (disease_data['Disease'] == 'Stroke') | (disease_data['Disease'] == 'Osteoporosis')
                      | (disease_data['Disease'] == 'Hypertension') | (disease_data['Disease'] == 'Diabetes') | (disease_data['Disease'] == 'Migraine')
                      | (disease_data['Disease'] == 'Influenza') | (disease_data['Disease'] == 'Pneumonia') | (disease_data['Disease'] == 'Bronchitis') | (disease_data['Disease'] == 'Hyperthyroidism')]
new_df

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,Yes,No,Yes,Yes,19,Female,Low,Normal,Positive
3,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
4,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
6,Influenza,Yes,Yes,Yes,Yes,25,Female,Normal,Normal,Positive
7,Influenza,Yes,Yes,Yes,Yes,25,Female,Normal,Normal,Positive
...,...,...,...,...,...,...,...,...,...,...
344,Stroke,Yes,No,Yes,No,80,Female,High,High,Positive
345,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
346,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
347,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive
348,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive

In [10]:
test_data = new_df[['Disease', 'Fever', 'Cough', 'Fatigue', 'Difficulty Breathing', 'Blood Pressure', 'Cholesterol Level']].copy()
test_data

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Blood Pressure,Cholesterol Level
0,Influenza,Yes,No,Yes,Yes,Low,Normal
3,Asthma,Yes,Yes,No,Yes,Normal,Normal
4,Asthma,Yes,Yes,No,Yes,Normal,Normal
6,Influenza,Yes,Yes,Yes,Yes,Normal,Normal
7,Influenza,Yes,Yes,Yes,Yes,Normal,Normal
...,...,...,...,...,...,...,...
344,Stroke,Yes,No,Yes,No,High,High
345,Stroke,Yes,No,Yes,No,High,High
346,Stroke,Yes,No,Yes,No,High,High
347,Stroke,Yes,No,Yes,No,High,High
348,Stroke,Yes,No,Yes,No,High,High